### ISSUE TITLE
yeoman generator not found with latest iojs version

### ISSUE THREAD

**Issue by interstellerS** [yeoman/yo#297]
Hi ,

Yeoman does not find generator indeed it's listed when running help .
This Figure shows the yeoman showing the generator but not enable to run them . 
![yeamanerror](https://cloud.githubusercontent.com/assets/10755262/6151859/f8a16856-b218-11e4-88c6-f336c68c84f6.png)

my configuration is listed on terminal printscreen (iojs 1.0.2 installed via nvm and ubuntu OS). THX.

**Comment by kevva** [comment]
Did you install the generator before or after you installed iojs? Try installing it again.

**Comment by SBoudrias** [comment]
Might be related to https://github.com/yeoman/environment/issues/30

**Comment by interstellerS** [comment]
@kevva  yup trying that also . same issue .

**Comment by SBoudrias** [comment]
This is now fixed, please update `yo` (`npm -g update`)

**Comment by interstellerS** [comment]
@SBoudrias  Works now thx .
Just curious what was the (issue,fix) .
Still have some permission denied errors tho . I guess it's another issue .

**Comment by SBoudrias** [comment]
@interstellerS an issue with text pattern substitution. You can check the issue I posted higher and the related PR.
