### ISSUE TITLE
Arrow keys not always working Windows 10 cmd

### ISSUE THREAD

**Issue by cveld** [yeoman/yo#360]
When I use yo from Windows 10 cmd, the arrow keys are not always working. It then sticks into some kind of readline history list. This is not always happening. Unfortunately I can't pinpoint what is causing it. Using yo version 1.4.8.

**Comment by SBoudrias** [comment]
This is reported on the Node repo https://github.com/nodejs/node/issues/2996

**Comment by fvilers** [comment]
Don't forget that you can select menu items by their index (one based).

**Comment by SBoudrias** [comment]
From the node bug, it looks like no keypress events at all are working on windows.

**Comment by cveld** [comment]
That is not true as most of the time I am perfectly able to walk through
the menus with the arrow keys. Somehow it gets stuck sometimes in some
floating input line itself and then all keypresses are flowing into this
floating input line instead of the registered event handlers.

2015-09-24 19:41 GMT+02:00 Simon Boudrias <notifications@github.com>:

**Comment by SBoudrias** [comment]
I meant, sometime windows just don't register them, and when that happen you don't receive any keypress event. The issue though is not always happening as sometime the keypress events are correctly fired.

**Comment by AysenZakharov** [comment]
I using "git bash" and i have same problem. But Windows Command Prompt works wery well.

**Comment by SBoudrias** [comment]
That have been fixed and shipped on Node.js side. https://github.com/nodejs/node/issues/2996

**Comment by Schandlich** [comment]
@SBoudrias Still appears to be broken.
Will not work for me on Node 5.8 and Yeoman 1.7
Can we reopen please? https://github.com/nodejs/node/issues/5384

**Comment by SBoudrias** [comment]
@Schandlich see the issue I just posted please.

**Comment by Schandlich** [comment]
@SBoudrias Thank you. That is where I found the link to nodejs/node#5384. :D

**Comment by AmirGilboa** [comment]
still broken here. :(

**Comment by csjcode** [comment]
It's broken for me in Git Bash, but seems to work in cmd.exe

$ npm -v
3.3.12

$ node -v
v5.5.0

>yo --version
1.7.0

**Comment by edgolub** [comment]
I'll just put a screenshot to express my feels:

![image](https://cloud.githubusercontent.com/assets/9299435/14541247/4aa39b4e-0289-11e6-902a-9db3bae4019d.png)

**Comment by dsouzadyn** [comment]
The issue has something to do with a recent windows update I think. It wasn't there few days ago.

**Comment by nyxjoel** [comment]
I have the same issue, there is someone who already solved it?

**Comment by SBoudrias** [comment]
@nyxjoel access the generator through the `yo` menu. The arrow bug is a regression in Node.js, they need to fix it on their side :(

**Comment by RonAlmog** [comment]
and they did. get the latest node, npm, and yo. at least in my case, it's been fixed.

**Comment by KammererTob** [comment]
Note: It is fixed in version >= 6.2.2. 
Not for 4.4.5, which they recommend for most users.

**Comment by normundy** [comment]
Still having this issue in Git Bash on Windows 10

**Comment by alegadpen** [comment]
Yep, issue still exists in Git Bash on Win10
I was able to bypass it one day, by setting some xterm function, sadfully I've lost it and now there's no way to make it work on Git Bash.

**Comment by RamonkHarrison** [comment]
www.Windows10KeySale.com

You can purchase from here: www.Windows10KeySale.com, 100% working!?

**Comment by mischah** [comment]
Reported as spam.

**Comment by dean0bambin0** [comment]
Has there been any fix for this?? Still happening for me on git bash windows 10

**Comment by SBoudrias** [comment]
Git Bash is not a TTY command line tool. As such, it doesn't support any interactive features.

You can use cmd, powershell, and a lot of other command line tool on Windows. Just make sure it is a TTY.

**Comment by dean0bambin0** [comment]
Ok Thanks, that's frustrating cause it works with git version 1.9.5.msysgit.0.

**Comment by prubini87** [comment]
Can this issue be reopened? I'm unable to use Yeoman in Windows 10.

$ yo --version
2.0.0

$ node -v
v8.1.0

Both Powershell and Command Prompt don't let me get past choosing options in the first menu. I can actually switch between them, but once I hit enter, it asks for a name for my project and then, when i type, nothing shows up, it's like it's not captuing my keyboard input... 

I read some of the messages above and I decided to try git bash, which showed a slightly different behavior, but ultimately also didn't get me through the first stages much less create the source code!

**Comment by CamiloTerevinto** [comment]
Exactly the same issue as @prubini87:

windows 10
npm -v         => 5.0.3
node -v        => v.8.1.0
yo --version => 2.0.0

I can select the first option using arrow keys, then 100% of the input is ignored. 
How can this be treated as solved if people is still getting this issue?

**Comment by SBoudrias** [comment]
@prubini87 @CamiloTerevinto looks like Node 8 broke the readline module again. You should report your issues there.

**Comment by prubini87** [comment]
@SBoudrias Yep, you may be right sir, I've rolled back to Node 6 and it's working just fine. It seems to be related to Node 8 indeed. Could you provide @CamiloTerevinto and I a link where we should report this, please?

**Comment by SBoudrias** [comment]
Bug was reported the Node https://github.com/nodejs/node/issues/13557 you can follow that issue to be notified once resolved.
